wandb:
  run_name: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF" #if you use openai api, put the name of model
  chat_template: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
  size_category: "30B≤"
  size: null
  release_date: "4/18/2024"