wandb:
  run_name: "CohereForAI/aya-expanse-8b" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "CohereForAI/aya-expanse-8b" #if you use openai api, put the name of model
  chat_template: "CohereForAI/aya-expanse-8b"
  size_category: "<10B"
  size: null
  release_date: "4/18/2024"