wandb:
  run_name: "turing-motors/Llama-3-heron-brain-70B-v0.3" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "turing-motors/Llama-3-heron-brain-70B-v0.3" #if you use openai api, put the name of model
  chat_template: "turing-motors/Llama-3-heron-brain-70B-v0.3"
  size_category: "30B≤"
  size: null
  release_date: "4/18/2024"