wandb:
  run_name: "mistralai/Mistral-Large-Instruct-2411" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthropic", "google", "cohere", "vllm", "mistral", "bedrock"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "mistralai/Mistral-Large-Instruct-2411" #if you use openai api, put the name of model
  chat_template: "mistralai/Mistral-Large-Instruct-2411"
  size_category: "30B≤"
  size: null
  release_date: "11/18/2024"