wandb:
  run_name: "Qwen/QwQ-32B-Preview" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Qwen/QwQ-32B-Preview" #if you use openai api, put the name of model
  chat_template: "Qwen/QwQ-32B-Preview"
  size_category: "30B≤"
  size: null
  release_date: "3/28/2024"